# Generated by Django 5.0.6 on 2024-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rententry',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
