# Generated by Django 5.0.6 on 2024-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rententry_cost_per_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rententry',
            old_name='electricity_units',
            new_name='current_electricity_units',
        ),
        migrations.AddField(
            model_name='rententry',
            name='last_electricity_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rententry',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
